version: '2'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  zookeeper:
    container_name: "zookeeper"
    image: wurstmeister/zookeeper:3.4.6
    ports:
     - "2181:2181"
    networks:
      - kafka-net
    restart: unless-stopped
     
  kafka:
    image: wurstmeister/kafka
    container_name: "kafka"
    ports:
     - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    restart: unless-stopped

networks:
  kafka-net:
    driver: bridge